accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug:slug>', views.article_detail, name="detail"),
    #path(r'^(?P<slug>[\w-]+)/$', views.article_detail),
    path('create/', views.article_create, name="create"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    #path('', views.homepage, name='homepage'),
    path('', article_views.article_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

# for image
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    # image
    thumb = models.ImageField(default='default.jpg', blank=True)

    # foreign key
    author = models.ForeignKey(User, default='1', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from .import models


class ArticleCreate(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = {'title', 'body', 'slug', 'thumb'}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    elif request.method == 'GET':
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    elif request.method == 'GET':
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from .import forms

# import login required decorator for any function or def after login call
from django.contrib.auth.decorators import login_required

# Create your views here.


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, "articles/article_list.html", {'articles': articles})


def article_detail(request, slug):
    # return HttpResponse(slug)

    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.ArticleCreate(request.POST, request.FILES)
        if form.is_valid():
            # save articel to do
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    elif request.method == 'GET':
        form = forms.ArticleCreate()
    return render(request, 'articles/article_create.html', {'form': form})

myblog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def about(request):
   # return HttpResponse('about')
    return render(request, "about.html")


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, "homepage.html")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

<!--Account-->

{% block content %}
<h1>Log in</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
  <!--form-->
  {{form}}
  <!--form-->
  {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}" />
  {% endif%}
  <input type="submit" value="Login" />
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

<!--Account-->

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %}
  <!--form-->
  {{form}}
  <input type="submit" value="Signup" />
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

<!--star-->
{% block content %}
<div class="article_create">
  <h2>Create an Awesome New Article</h2>
  <form
    class="site-form"
    action="{% url 'articles:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <!--form-->
    {{form}}

    <input type="submit" value="Create" />
  </form>
  <script src="/static/slugify.js"></script>
</div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}

<!--start-->

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{article.thumb.url}}" alt="{{article.thumb}}" />
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

<!-- this extending-->

{% block content %}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2>
      <a href="{% url 'articles:detail' slug=article.slug %}"
        >{{article.title}}</a
      >
    </h2>
    <p><a href="#">{{article.snippet}}</a></p>
    <!-- <h3><a href="#">{{article.slug}}</a></h3> -->
    <p><a href="#">{{article.date}}</a></p>
    <p class="author">added by {{article.author.username}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
  </body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Article List</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <header class="wrapper">
      <h1>
        <a class="article_list_img" href="{% url 'home' %}"
          >Talks
          <!-- <img src="{% static 'blogger-logo.svg' %}" /> -->
          <i class="fab fa-blogger-b"></i>Techy
        </a>
      </h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form
              class="logout-link"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li>
            <a
              class="highlight"
              href="{% url 'articles:create' %}"
              class="highlight"
              >New Article</a
            >
          </li>
          {% else %}
          <li>
            <a href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>

          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %} {% endblock %}
    </div>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home Page</title>
  </head>
  <body>
    <h1>Home Page</h1>
  </body>
</html>